# Generated by Django 2.2 on 2022-03-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articel',
            new_name='Events',
        ),
    ]
