# Generated by Django 2.2 on 2022-03-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0004_events_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
