# Generated by Django 2.2 on 2022-03-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0002_auto_20220309_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_picture'),
        ),
        migrations.AddField(
            model_name='events',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
